### PR TITLE
Add Turkish description for MSA

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Review by 1024jp — APPROVED** [review]

**Comment by 1024jp** [comment]
Thank you!

**Comment by bitigchi** [comment]
> Thank you!

My pleasure!

**Comment by bitigchi** [comment]
In addition, the app subtitle for the App Store could be translated as such:

"Hafif bir düz metin düzenleyici"

Also, in one of the screenshots, "Font" translation is still the old one... Do you want me to submit an updated image for that? Sorry, that slipped before my eyes...

**Comment by 1024jp** [comment]
@bitigchi Thank you for the update.
I've just updated the repo.
The display in the App Store will be updated when releasing the next CotEditor (4.1.2) since it is the only chance to change the information in the MAS.

> Also, in one of the screenshots, "Font" translation is still the old one...

Oh, ok. You are right. I'll also do that later.

**Comment by bitigchi** [comment]
Thank you, much appreciated!

**Comment by 1024jp** [comment]
@bitigchi Hi, I was about to update the subtitle in the MAS for the next release, but then realized the line must be less than 30 characters. The current Turkish subtitle, "Hafif bir düz metin düzenleyici," is however unfortunately 31 characters. Could you suggest another one that has less than 30 characters?

**Comment by bitigchi** [comment]
Thanks for letting me know. In that case "Hafif bir metin düzenleyici" should suffice.

**Comment by 1024jp** [comment]
@bitigchi Thank you! I'll update it on the release for v4.1.3.

**Comment by bitigchi** [comment]
Actually, let's make it "Hafif düz metin düzenleyici". This makes sure "plain" is stressed.

Edit: Oh I see that you committed already. It's up to you then, first one is more akin "A lightweight text editor", and the second one is more close to the original one. Your call. :)

**Comment by 1024jp** [comment]
Thank you for the commend and sorry for my late reply. Following your suggestion, I've changed the Turkish subtitle to "Hafif düz metin düzenleyici" in the latest CotEditor, version 4.1.3.

**Comment by bitigchi** [comment]
> 1024jp ***@***.***> şunları yazdı (19 Mar 2022 05:42):
> 
> 
> Thank you for the commend and sorry for my late reply. Following your suggestion, I've changed the Turkish subtitle to "Hafif düz metin düzenleyici" in the latest CotEditor, version 4.1.3.

Yep, I’ve noticed. Thank you very much!

**Pull request merged**
